Repository astarte-platform/astarte-device-sdk-esp32, pull requests merged in 2020-02, with the labels that each got.

#5 Handle certificate expiration
  CHANGELOG.md
  astarte_credentials.c
  astarte_device.c
  include/astarte_credentials.h
Labels: bug, critical

#6 astarte_pairing: do not try to print a NULL json_error
  CHANGELOG.md
  astarte_pairing.c
Labels: bug

#7 Prepare 0.11.0-rc.0 release
  CHANGELOG.md
Labels: chore
