Repository astarte-platform/astarte-device-sdk-esp32, pull requests merged in 2020-04, with the labels that each got.

#15 Add more flexibility for credentials secret
  CHANGELOG.md
  astarte_credentials.c
  astarte_device.c
  astarte_pairing.c
  include/astarte_credentials.h
  include/astarte_device.h
  include/astarte_pairing.h
Labels: enhancement, user experience

#16 astarte_device: free resources earlier in init_connection
  astarte_device.c
Labels: enhancement, performance

#18 astarte_device: add astarte_device_is_connected
  CHANGELOG.md
  astarte_device.c
  include/astarte_device.h
Labels: API, enhancement

#20 Prepare v0.11.0 release
  CHANGELOG.md
Labels: chore

#22 astarte_device: add astarte_device_stream_aggregate
  CHANGELOG.md
  astarte_device.c
  include/astarte_device.h
Labels: enhancement, main feature

#21 astarte_bson_serializer: fix little endian to host conversion
  CHANGELOG.md
  astarte_bson_serializer.c
Labels: bug

#23 astarte_device: fix astarte_device_stream_aggregate
  astarte_device.c
Labels: bug

#24 astarte_device: add astarte_device_unset_path function
  CHANGELOG.md
  astarte_device.c
  include/astarte_device.h
Labels: enhancement, main feature
