Repository astarte-platform/astarte-device-sdk-esp32, pull requests merged in 2020-05, with the labels that each got.

#25 astarte_hwid: allow using UUIDv5 to derive the hardware ID
  CHANGELOG.md
  Kconfig
  astarte_hwid.c
Labels: enhancement

#26 Add support for esp-idf 4.0 build system
  CHANGELOG.md
  CMakeLists.txt
  astarte_device.c
  examples/toggle_led/CMakeLists.txt
  examples/toggle_led/main/CMakeLists.txt
Labels: enhancement

#31 astarte_device: add wrappers to set values on properties interfaces
  CHANGELOG.md
  astarte_device.c
  include/astarte_device.h
Labels: enhancement, user experience

#33 Forward port changes from v0.11
  CHANGELOG.md
  astarte_credentials.c
  astarte_device.c
  astarte_hwid.c
  astarte_pairing.c
  include/astarte.h
  include/astarte_device.h
Labels: chore

#35 Prepare 0.11.1 release
  CHANGELOG.md
Labels: chore
