Repository astarte-platform/astarte-device-sdk-esp32, pull requests merged in 2020-03, with the labels that each got.

#8 astarte_pairing: close nvs after we're done with it
  astarte_pairing.c
Labels: bug

#9 astarte_device: free all resources after a failure
  astarte_device.c
Labels: bug

#10 Reduce memory footprint
  CHANGELOG.md
  astarte_credentials.c
  astarte_device.c
  astarte_pairing.c
  examples/toggle_led/main/app_main.c
  include/astarte_credentials.h
Labels: performance

#11 astarte_credentials: use ECDSA keys instead of RSA keys
  CHANGELOG.md
  astarte_credentials.c
Labels: enhancement, performance

#12 Fix superflous reinit
  CHANGELOG.md
  Kconfig
  astarte_device.c
Labels: bug

#13 Prepare v0.11.0-rc.1
  CHANGELOG.md
Labels: chore
