Repository astarte-platform/astarte-device-sdk-esp32, pull requests merged in 2021-03, with the labels that each got.

#56 astarte_device: add astarte_device_stop function
  CHANGELOG.md
  astarte_device.c
  include/astarte_device.h
Labels: API, enhancement

#57 astarte_device: add user connection/disconnection callbacks
  CHANGELOG.md
  astarte_device.c
  examples/toggle_led/main/app_main.c
  include/astarte_device.h
Labels: enhancement

#58 astarte_device: return astarte_err_t from astarte_device_start
  CHANGELOG.md
  astarte_device.c
  examples/toggle_led/main/app_main.c
  include/astarte_device.h
Labels: API, enhancement

#59 app_main: run clang-format
  examples/toggle_led/main/app_main.c
Labels: chore

#60 Use stdbool
  astarte_bson.c
  astarte_bson_serializer.c
  astarte_credentials.c
  include/astarte_bson.h
  include/astarte_bson_serializer.h
  include/astarte_credentials.h
Labels: API, documentation

#62 Readme and doc revamp
  .github/workflows/docs-workflow.yaml
  .gitignore
  README.md
  doc/astarte-device-sdk-esp32.doxy
  doc/docmain.dox
  examples/toggle_led/README.md
Labels: documentation

#65 Prepare 1.0.0 beta.2
  CHANGELOG.md
  include/astarte.h
Labels: chore
